i3-msg 'workspace 2-Doc; exec i3-sensible-terminal'
i3-msg 'workspace 3-Net; exec firefox'
i3-msg 'workspace 4-Slack; exec slack'
i3-msg 'workspace 5-Mail; exec thunderbird'
i3-msg 'workspace 6-Sound; exec gnome-terminal -x alsamixer'
i3-msg 'workspace 8-*top; exec gnome-terminal -x vtop'
i3-msg 'workspace 9-Dump; exec i3-sensible-terminal'
i3-msg 'workspace 1-Work; exec i3-sensible-terminal focus'
